import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  guideSidebar: [
    'getting-started',
    'html-views',
    'view-lifecycle',
    'modern-frameworks',
    'examples',
    'limitations',
    '1.0-vs-2.0',
    'papyrus-bridge',
    'translations',
    'vanilla-ui-suppression',
    'model-preview',
    'view-watchdog',
    'networking',
    'panel-management',
    'api-reference',
    'changelog',
  ],
  apiSidebar: [
    {
      type: 'autogenerated',
      dirName: 'api',
    },
  ],
};

export default sidebars;
